# Day 29 - NumPy基础


## 今日总结

今天系统整理NumPy数组基础，包括数组创建、dtype、内存、维度、shape、reshape和索引切片，为后续矩阵运算与PyTorch Tensor做准备。


**主要掌握：**

* `np.array()`
* ndarray
* dtype
* `float32`
* `nbytes`
* `ndim`
* `shape`
* 多维索引
* 切片
* `reshape()`
* `-1`推断
* `zeros()`
* `ones()`
* `arange()`
* `linspace()`


**详细理解：**

1. **ndarray为批量数值计算设计**

   理解：相比Python列表，它强调同类型数据和向量化计算。

2. **shape描述数据结构**

   理解：机器学习中batch和feature都通过shape表达。

3. **dtype影响精度和内存**

   理解：float32在深度学习中非常常见。

4. **reshape只重组形状**

   理解：元素总数必须保持一致。


**今天最大的收获：**

> NumPy开始让数据具有明确的shape和dtype，而不只是Python容器。


**通过今天的学习，我理解了：**

* shape是AI数据流核心
* 多维索引必须熟练
* reshape常用于模型输入调整
* 数组创建函数可以快速生成测试数据


**今天开始从：**

> 使用list理解所有数据


**转向：**

> 使用ndarray的维度、类型和形状理解数值数据。


# 学习内容与代码实践


## 1. NumPy向量化初体验

保留原代码。


In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a*2)    #将数组a中的每个元素乘以2


[2 4 6]


## 2. dtype与内存

保留原代码。


In [ ]:
import numpy as np
#numpy的数据类型：int,float,bool,object,string
array=np.array([1,2,3,4,5],dtype=np.float32)

print(array)
print(array.dtype) #查看数组的元素类型
print(f"{array.nbytes} bytes")#查看数组占用的字节数

[1. 2. 3. 4. 5.]
float32
20 bytes


## 3. ndim与shape

保留原代码。


In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array.ndim) #查看数组的维度
array = np.array([['a','b','c'],['d','e','f']])
print(array.ndim)
array = np.array([[['a','b','c'],['d','e','f']],[['g','h','i'],['j','k','l']]])#创建一个三维数组
print(array.ndim)
print(array.shape)
print(array[0,0,0]) #查看数组的第一个元素


1
2
3
(2, 2, 3)
a


## 4. reshape说明

保留原代码。


In [2]:
#reshape()函数可以改变数组的形状
import numpy as np  
arrat = np.array([1,2,3,4,5,6])
print(arrat)
print(arrat.shape)
print(arrat.reshape(2,3))
print(arrat.reshape(3,-1))#-1表示自动计算列数


[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


## 5. 索引、切片与reshape

保留原代码。


In [5]:
import numpy as np
#numpy的索引和切片
array = np.array([1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16])
array = array.reshape(4, 4)
print(array[0:2]) #切片，取前两行
print(array[:, -1]) #切片，取最后一列
print(array[0,0])


[[1 2 3 4]
 [5 6 7 8]]
[ 4  8 12 16]
1


## 6. 常用创建函数

补齐高频API。


In [ ]:
import numpy as np

print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
