# Day 30 - NumPy进阶计算


## 今日总结

今天继续NumPy向量化、广播、axis、聚合、布尔筛选和保存读取，并补齐矩阵乘法、转置、view/copy这些进入PyTorch前非常重要的知识。


**主要掌握：**

* 标量运算
* 向量化
* 广播
* 聚合
* `axis=0/1`
* 布尔索引
* `np.where()`
* `np.save()`
* `np.load()`
* `np.savez()`
* 转置 `.T`
* 矩阵乘法 `@`
* view vs copy


**详细理解：**

1. **向量化避免Python层循环**

   理解：一次把规则应用到整块数组。

2. **广播按尾部维度匹配**

   理解：维度相等或其中一个为1时通常可兼容。

3. **axis表示被压缩的轴**

   理解：二维数组axis=0得到每列聚合，axis=1得到每行聚合。

4. **元素乘法和矩阵乘法不同**

   理解：`*`逐元素，`@`执行线性代数乘法。

5. **view可能共享底层数据**

   理解：修改切片可能影响原数组。


**今天最大的收获：**

> NumPy真正重要的是shape规则、向量化和矩阵计算模型。


**通过今天的学习，我理解了：**

* 广播减少显式复制
* 布尔数组要用逐元素逻辑组合
* 矩阵乘法要求内维匹配
* copy/view决定数据是否共享


**今天开始从：**

> 把NumPy当更快的list


**转向：**

> 按照向量、轴和矩阵规则理解数组计算。


# 学习内容与代码实践


## 1. 标量运算

保留原代码。


In [ ]:
import numpy as np
#numpy的标量计算
array = np.array([1, 2, 3])
print(array + 1) #每个元素加1
print(array * 2) #每个元素乘以2
print(array **3) #每个元素的立方


[2 3 4]
[2 4 6]
[ 1  8 27]


## 2. 向量运算

保留原代码。


In [1]:
import numpy as np
#numpy的向量计算
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2) #对应元素相加    
print(array1 * array2) #对应元素相乘
print(np.pi*array1**2) #每个元素的圆的面积
print(np.sqrt(array1)) #每个元素的平方根
array1[array1>2] = 0 #将大于2的元素赋值为0
print(array1)

[5 7 9]
[ 4 10 18]
[ 3.14159265 12.56637061 28.27433388]
[1.         1.41421356 1.73205081]
[1 2 0]


## 3. 广播

保留原代码。


In [ ]:
import numpy as np
#numpy的广播机制,从右往左匹配相同或者其中一个数组有维度为1，则可以广播
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([1, 2, 3])
print(array1.shape) #查看数组的形状
print(array2.shape) #查看数组的形状
print(array1 + array2) #对应元素相加
print(array1 * array2) #对应元素相乘


(2, 3)
(3,)
[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]


## 4. 聚合

保留原代码。


In [ ]:
import numpy as np
#常用的聚合函数
array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(array)) #求和
print(np.sum(array, axis=0)) #求列方向和
print(np.mean(array)) #求平均值

21
[ 6 15]
3.5


## 5. 条件筛选

原代码和注释保持不变。注意：NumPy中使用 `&` 不是因为“底层是C”，而是比较结果是布尔数组，`&` 被重载为逐元素组合；Python `and` 要求整体真值。


In [12]:
import numpy as np
#过滤数组
ages=np.array([[21,17,19,20,16,30,18,65],[39,22,15,99,18,19,20,21]])
teenagers = ages[ages < 18]
print(teenagers)
adults = ages[(ages >= 18) & (ages < 65)]#numpy是基于C语言实现的，所以要用&不能用and
print(adults)
#置换
print(np.where(ages < 18, 0, ages)) #将小于18的元素置为0


[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


## 6. 保存与读取

原代码和注释保持不变。注意：`np.array('[1, 2, 3], [4, 5, 6]')` 创建的是字符串标量数组，不会自动变成二维数值数组。


In [20]:
import numpy as np
#numpy数组的保存和读取
array = np.array([[1, 2, 3], [4, 5, 6]])
np.save('array.md', array) #保存数组    
array2 = np.load('array.md.npy') #加载数组，numpy会自动在文件名后加上.npy
print(array2)
array3 = np.array('[1, 2, 3], [4, 5, 6]') 
np.savez('array.npz', array2, array3) #保存多个数组
array4 = np.load('array.npz') #加载多个数组
print(array4['arr_0']) #加载第一个数组
print(array4['arr_1']) #加载第二个数组


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1, 2, 3], [4, 5, 6]


## 7. `axis=0` 与 `axis=1`

补齐轴概念。


In [ ]:
import numpy as np

array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 压缩第0轴：每列聚合
print(np.sum(array, axis=0))

# 压缩第1轴：每行聚合
print(np.sum(array, axis=1))


## 8. 转置与矩阵乘法

PyTorch前必须掌握。


In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(a.T)

# (2, 3) @ (3, 2) -> (2, 2)
print(a @ b)

# * 是逐元素操作
print(a * 2)


## 9. view与copy

理解数据共享。


In [ ]:
import numpy as np

original = np.array([1, 2, 3, 4])

# 切片通常是view
view = original[1:3]
view[0] = 99

print(original)
print(view)

# copy创建独立数组
copied = original[1:3].copy()
copied[0] = 1000

print(original)
print(copied)
