<font size="7">8月9号</font>

# Day 33 - NumPy基础（Numerical Python）


## 今日总结

今天学习了 Python 科学计算库 NumPy 的基础使用，理解了 NumPy 数组与 Python 列表之间的区别，掌握了数组创建、维度管理、数组运算、广播机制、数据筛选以及数组保存等核心内容。


**主要掌握：**

* NumPy库的作用以及 `ndarray` 数组结构
* 使用 `np.array()` 创建 NumPy 数组
* 使用 `dtype` 设置和查看数组数据类型
* 使用 `nbytes` 查看数组占用内存大小
* 使用 `ndim` 查看数组维度数量
* 使用 `shape` 查看数组结构
* 使用 `reshape()` 改变数组形状
* 使用 `-1` 自动推断数组维度
* NumPy数组索引和切片操作
* NumPy中的标量计算
* NumPy中的向量化计算
* NumPy广播机制
* 使用 `sum()`、`mean()` 等聚合函数
* 使用条件筛选过滤数组数据
* 使用 `where()` 对数组进行条件处理
* 使用 `save()`、`load()`、`savez()` 保存和读取数组


**详细理解：**

1. **NumPy数组替代Python列表进行高效计算**

   理解：Python列表适合存储普通数据，但大量数值计算时需要循环处理。NumPy通过 `ndarray` 提供向量化计算能力，例如 `array * 2` 可以直接让数组中所有元素同时计算，提高数据处理效率。


2. **数组维度和shape是理解AI数据结构的基础**

   理解：NumPy中的 `ndim` 表示数组维度数量，`shape` 表示每个维度的大小。例如二维数组的 `shape` 可以表示为 `(2,3)`。这种维度思想与后续学习 PyTorch 中 Tensor 的数据结构高度相关。


3. **reshape可以改变数据结构但不会改变数据内容**

   理解：`reshape()` 可以重新组织数组形状，例如将一维数组转换为二维矩阵。通过 `reshape(3,-1)` 可以让 NumPy 自动计算未知维度，这种方式在数据预处理和模型输入调整中非常常见。


4. **广播机制让不同形状的数据进行计算**

   理解：NumPy可以根据数组形状自动扩展数据进行计算，例如 `(2,3)` 的数组和 `(3,)` 的数组可以直接相加。广播机制减少了手动循环，是深度学习矩阵计算的重要思想。


5. **NumPy提供完整的数据处理流程**

   理解：NumPy不仅可以进行数学计算，还可以完成数据筛选、条件替换和数据保存。例如通过条件索引筛选满足要求的数据，通过 `np.save()` 保存计算结果，为后续数据分析和模型训练提供基础。


**今天最大的收获：**

> NumPy让我开始理解数据不只是简单的变量，而是具有维度、结构和计算规则的数据对象，这是进入机器学习和深度学习计算的重要基础。


**通过今天的学习，我理解了：**

* 数组结构比普通列表更适合处理大规模数值数据
* 数据维度和shape是机器学习数据流中的核心概念
* 向量化计算可以减少循环，提高计算效率
* 广播机制连接了数组计算和深度学习中的张量计算
* 数据处理不仅包括计算，也包括筛选、转换和保存


**今天开始从：**

> 使用Python基础数据结构处理数据


**转向：**

> 使用面向科学计算的数据结构理解和处理数据，为学习Pandas和PyTorch建立基础。


---

以后 NumPy、Pandas、PyTorch 这些内容我都会按照这个版本记录，不再改格式。你原来的 Day 26～32 那种风格更适合长期作为 GitHub 学习日志。

In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a*2)    #将数组a中的每个元素乘以2


[2 4 6]


In [ ]:
import numpy as np
#numpy的数据类型：int,float,bool,object,string
array=np.array([1,2,3,4,5],dtype=np.float32)

print(array)
print(array.dtype) #查看数组的元素类型
print(f"{array.nbytes} bytes")#查看数组占用的字节数

[1. 2. 3. 4. 5.]
float32
20 bytes


In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array.ndim) #查看数组的维度
array = np.array([['a','b','c'],['d','e','f']])
print(array.ndim)
array = np.array([[['a','b','c'],['d','e','f']],[['g','h','i'],['j','k','l']]])#创建一个三维数组
print(array.ndim)
print(array.shape)
print(array[0,0,0]) #查看数组的第一个元素


1
2
3
(2, 2, 3)
a


In [2]:
#reshape()函数可以改变数组的形状
import numpy as np  
arrat = np.array([1,2,3,4,5,6])
print(arrat)
print(arrat.shape)
print(arrat.reshape(2,3))
print(arrat.reshape(3,-1))#-1表示自动计算列数


[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
import numpy as np
#numpy的索引和切片
array = np.array([1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15,16])
array = array.reshape(4, 4)
print(array[0:2]) #切片，取前两行
print(array[:, -1]) #切片，取最后一列
print(array[0,0])


[[1 2 3 4]
 [5 6 7 8]]
[ 4  8 12 16]
1


In [ ]:
import numpy as np
#numpy的标量计算
array = np.array([1, 2, 3])
print(array + 1) #每个元素加1
print(array * 2) #每个元素乘以2
print(array **3) #每个元素的立方


[2 3 4]
[2 4 6]
[ 1  8 27]


In [1]:
import numpy as np
#numpy的向量计算
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(array1 + array2) #对应元素相加    
print(array1 * array2) #对应元素相乘
print(np.pi*array1**2) #每个元素的圆的面积
print(np.sqrt(array1)) #每个元素的平方根
array1[array1>2] = 0 #将大于2的元素赋值为0
print(array1)

[5 7 9]
[ 4 10 18]
[ 3.14159265 12.56637061 28.27433388]
[1.         1.41421356 1.73205081]
[1 2 0]


In [ ]:
import numpy as np
#numpy的广播机制,从右往左匹配相同或者其中一个数组有维度为1，则可以广播
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([1, 2, 3])
print(array1.shape) #查看数组的形状
print(array2.shape) #查看数组的形状
print(array1 + array2) #对应元素相加
print(array1 * array2) #对应元素相乘


(2, 3)
(3,)
[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]


In [ ]:
import numpy as np
#常用的聚合函数
array = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(array)) #求和
print(np.sum(array, axis=0)) #求列方向和
print(np.mean(array)) #求平均值

21
[ 6 15]
3.5


In [12]:
import numpy as np
#过滤数组
ages=np.array([[21,17,19,20,16,30,18,65],[39,22,15,99,18,19,20,21]])
teenagers = ages[ages < 18]
print(teenagers)
adults = ages[(ages >= 18) & (ages < 65)]#numpy是基于C语言实现的，所以要用&不能用and
print(adults)
#置换
print(np.where(ages < 18, 0, ages)) #将小于18的元素置为0


[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]


In [20]:
import numpy as np
#numpy数组的保存和读取
array = np.array([[1, 2, 3], [4, 5, 6]])
np.save('array.md', array) #保存数组    
array2 = np.load('array.md.npy') #加载数组，numpy会自动在文件名后加上.npy
print(array2)
array3 = np.array('[1, 2, 3], [4, 5, 6]') 
np.savez('array.npz', array2, array3) #保存多个数组
array4 = np.load('array.npz') #加载多个数组
print(array4['arr_0']) #加载第一个数组
print(array4['arr_1']) #加载第二个数组


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1, 2, 3], [4, 5, 6]


<font size="7">8月13号</font>